#!/bin/bash

echo "ImageMagickをインストールしてから画像の余白をトリミングします"
echo "以下のコマンドを実行してください:"
echo ""
echo "1. ImageMagickのインストール:"
echo "   brew install imagemagick"
echo ""
echo "2. 画像の余白をトリミング:"
echo "   cd public/images/tarot-cards"
echo "   for f in *.jpg; do"
echo "     # バックアップを作成"
echo "     cp \"\$f\" \"\${f%.jpg}_original.jpg\""
echo "     # 余白をトリミング"
echo "     convert \"\$f\" -trim +repage \"\$f\""
echo "   done"
echo ""
echo "注意: -trim オプションは周囲の同じ色のピクセルを自動的に削除します"
echo "     +repage オプションは画像のキャンバスサイズをリセットします"